import { describe, it, expect } from "vitest";
import { readFile } from "node:fs/promises";
import { readSkin } from "./read";
import { writeSkin } from "./write";
import { checkRoundTrip } from "./roundtrip";
import { convertSkin } from "../convert/convert";
import { parseIni } from "../ini/document";
import { allSections, get, readSection } from "../ini/access";
import type { SkinPackage } from "./types";

/**
 * End-to-end against real archives in `samples/`, generated by
 * `scripts/make-samples.py`. The unit tests use synthetic in-memory packages;
 * these exercise the actual zip layer, which is where path casing, nested
 * roots and compression modes go wrong.
 *
 * Image bytes pass through unprocessed here — canvas only exists in a browser.
 */
async function load(name: string): Promise<SkinPackage> {
  const bytes = await readFile(new URL(`../../../samples/${name}`, import.meta.url));
  return readSkin(new File([bytes], name));
}

function sectionOf(pkg: SkinPackage, name: string) {
  const doc = parseIni(pkg.iniSource!);
  const slice = allSections(doc).find((s) => s.name.toLowerCase() === name.toLowerCase());
  return slice ? readSection(doc, slice) : {};
}

describe("sample .qs", () => {
  it("reads as a Quaver skin", async () => {
    const pkg = await load("sample-quaver.qs");
    expect(pkg.format).toBe("quaver");
    expect(pkg.entries.length).toBeGreaterThan(20);
    expect(pkg.iniPath).toBe("skin.ini");
  });

  it("round-trips its skin.ini byte-for-byte", async () => {
    const pkg = await load("sample-quaver.qs");
    expect(checkRoundTrip(pkg)?.iniStable).toBe(true);
  });

  it("survives a re-zip and re-read unchanged", async () => {
    const original = await load("sample-quaver.qs");
    const blob = await writeSkin(original);
    const again = await readSkin(new File([await blob.arrayBuffer()], "sample-quaver.qs"));

    expect(again.entries.length).toBe(original.entries.length);
    expect(again.iniSource).toBe(original.iniSource);

    const before = new Map(original.entries.map((e) => [e.path, e.bytes.length]));
    for (const entry of again.entries) {
      expect(before.get(entry.path)).toBe(entry.bytes.length);
    }
  });

  it("converts to a loadable osu! skin", async () => {
    const { pkg } = await convertSkin(await load("sample-quaver.qs"));
    expect(pkg.format).toBe("osu");

    const mania = sectionOf(pkg, "Mania");
    expect(mania["Keys"]).toBe("4");
    expect(mania["NoteBodyStyle"]).toBe("0");
    // 90 Quaver units -> 56.25 osu!px.
    expect(mania["ColumnWidth"]).toBe("56.25,56.25,56.25,56.25");
  });

  it("finds every element the sample actually ships", async () => {
    const { report } = await convertSkin(await load("sample-quaver.qs"));
    const missing = [...new Set(report.entries.filter((e) => e.status === "missing").map((e) => e.elementId))];

    // The sample deliberately omits column and hold lighting, so this is the
    // exact expected set — asserting it by name catches a resolver regression
    // that a bare `missing === 0` check would hide behind a changed fixture.
    expect(missing.sort()).toEqual(["columnLight", "holdLighting"].sort());

    // Everything the sample does ship must resolve, notes and receptors included.
    const shipped = [
      "note", "holdHead", "holdBody", "holdTail",
      "receptorUp", "receptorDown", "stageHint",
      "judge-marv", "judge-miss",
    ];
    for (const id of shipped) {
      const rows = report.entries.filter((e) => e.elementId === id);
      expect(rows.length).toBeGreaterThan(0);
      expect(rows.every((r) => r.status !== "missing")).toBe(true);
    }
  });

  it("locates the @1x4 spritesheet without treating it as absent", async () => {
    const { report } = await convertSkin(await load("sample-quaver.qs"));
    const lighting = report.entries.find((e) => e.elementId === "hitLighting");
    expect(lighting?.status).not.toBe("missing");
    expect(lighting?.from).toMatch(/hitlighting@1x4\.png$/i);
  });

  it("drops Quaver-only elements explicitly rather than silently", async () => {
    const { report } = await convertSkin(await load("sample-quaver.qs"));
    const dropped = report.entries.filter((e) => e.status === "dropped").map((e) => e.elementId);
    expect(dropped).toContain("stageBgMask");
    expect(dropped).toContain("stageDistant");
  });

  it("keeps each lane's art distinct through the conversion", async () => {
    const { pkg } = await convertSkin(await load("sample-quaver.qs"));
    const mania = sectionOf(pkg, "Mania");
    const referenced = [0, 1, 2, 3].map((n) => mania[`NoteImage${n}`]);
    expect(new Set(referenced).size).toBe(4);

    const names = new Set(pkg.entries.map((e) => e.path));
    for (const stem of referenced) expect(names.has(`${stem}.png`)).toBe(true);
  });

  it("packs the converted skin into a readable .osk", async () => {
    const { pkg } = await convertSkin(await load("sample-quaver.qs"));
    const blob = await writeSkin(pkg);
    const reread = await readSkin(new File([await blob.arrayBuffer()], "converted.osk"));
    expect(reread.format).toBe("osu");
    expect(checkRoundTrip(reread)?.iniStable).toBe(true);
  });
});

describe("sample .osk", () => {
  it("reads as an osu! skin and finds both keymodes", async () => {
    const pkg = await load("sample-osu.osk");
    expect(pkg.format).toBe("osu");
    expect(checkRoundTrip(pkg)?.keymodes).toEqual(["4K", "7K"]);
  });

  it("converts to Quaver with a section per keymode", async () => {
    const { pkg, report } = await convertSkin(await load("sample-osu.osk"));
    expect(pkg.format).toBe("quaver");
    expect(report.keymodes).toEqual(["4K", "7K"]);

    const doc = parseIni(pkg.iniSource!);
    const names = allSections(doc).map((s) => s.name);
    expect(names).toContain("4K");
    expect(names).toContain("7K");
    // 30 osu!px -> 48 Quaver units.
    expect(get(doc, allSections(doc).find((s) => s.name === "4K")!, "ColumnSize")).toBe("48");
  });

  it("expands the 1/2/S pattern into four distinct lane files", async () => {
    const { pkg } = await convertSkin(await load("sample-osu.osk"));
    const names = new Set(pkg.entries.map((e) => e.path.toLowerCase()));
    for (const lane of [1, 2, 3, 4]) {
      expect(names.has(`4k/hitobjects/note-hitobject-${lane}.png`)).toBe(true);
    }
  });

  it("warns that osu! lane background colours cannot survive", async () => {
    const { report } = await convertSkin(await load("sample-osu.osk"));
    expect(report.warnings.join(" ")).toMatch(/lane background colours/i);
  });

  it("reports the 7K lanes as missing rather than inventing them", async () => {
    // The sample only ships 4K-worth of elements, and osu!'s 7K pattern needs
    // the same two tokens — so nothing should be missing for notes, but the
    // report must not claim more than it copied.
    const { report } = await convertSkin(await load("sample-osu.osk"));
    const sevenK = report.entries.filter((e) => e.keymode === "7K");
    expect(sevenK.length).toBeGreaterThan(0);
    expect(sevenK.every((e) => e.status !== "synthesized")).toBe(true);
  });
});
